let g:a = 0
fu! s:load(module)
  exec 'source ' fnameescape(expand('~/.vim/modules/' . a:module . '.vim'))
endfu

" call s:load('init')
call s:load('bundles')
if has('nvim')
  call s:load('ncompletion')
else
  call s:load('completion')
endif

call s:load('options')
call s:load('autocmds')
call s:load('statusline')
call s:load('unite')

call s:load('plugins')
call s:load('mappings')

call s:load('helpers')
call s:load('misc')

call s:load('colors')
