#!/bin/sh

echo $2 | sed "s@^$HOME@~@" | awk -v len=$1 '{ _=len-length($0);r=int(_ / 2);l=_/2; if (length($0) > len) print ".."substr($0, length($0)-len+3,length($0)-1); else printf "%*s%s%*s\n",l,"",$0,r,""; }'
